SELECT b.CATEGORY, SUM(s.total_sales) AS TOTAL_SALES
FROM BOOK b
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS total_sales
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01'
      AND SALES_DATE < '2022-02-01'
    GROUP BY BOOK_ID
) s ON s.BOOK_ID = b.BOOK_ID
group by CATEGORY
ORDER BY CATEGORY;
