SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES from REST_INFO r
join (select FOOD_TYPE,  max(FAVORITES) AS MAX_FAV from REST_INFO group by FOOD_TYPE) m 
ON r.FOOD_TYPE = m.FOOD_TYPE
AND r.FAVORITES = m.MAX_FAV
order by r.FOOD_TYPE desc;
