SELECT 
    COUNT(*) AS FISH_COUNT,
    MONTH(STR_TO_DATE(REPLACE(TIME, '/', '-'), '%Y-%m-%d')) AS MONTH
FROM FISH_INFO
WHERE TIME IS NOT NULL
GROUP BY MONTH(STR_TO_DATE(REPLACE(TIME, '/', '-'), '%Y-%m-%d'))
ORDER BY MONTH(STR_TO_DATE(REPLACE(TIME, '/', '-'), '%Y-%m-%d'));
