SELECT 
YEAR(DIFFERENTIATION_DATE) as YEAR,
(SELECT max(SIZE_OF_COLONY) from ECOLI_DATA where YEAR(DIFFERENTIATION_DATE) = YEAR(a.DIFFERENTIATION_DATE) ) - a.SIZE_OF_COLONY as YEAR_DEV,
ID
from ECOLI_DATA a
ORDER BY YEAR ASC, YEAR_DEV ASC;
