SELECT FLAVOR
FROM (
    SELECT 
        f.FLAVOR,
        (f.TOTAL_ORDER + SUM(j.TOTAL_ORDER)) AS TOTAL_SUM
    FROM FIRST_HALF f
    JOIN JULY j 
        ON f.FLAVOR = j.FLAVOR
    GROUP BY f.FLAVOR, f.TOTAL_ORDER
    ORDER BY TOTAL_SUM DESC
    LIMIT 3
) AS ranked;
