SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*) >= 2
ORDER BY NAME;

-- SELECT NAME, COUNT(NAME) AS COUNT
-- FROM ANIMAL_INS
-- GROUP BY NAME
-- HAVING COUNT(NAME) >= 2
-- ORDER BY NAME;
